### ISSUE TITLE
Refresh of live-scoring pages. 

### ISSUE THREAD

**Issue by cmacfarl** [adwiii/nc-ftc-inspection-spark#5]
I ran some practice matches with a few teams in our workshop last weekend and one thing I noticed that could be problematic is that the scorekeeping tablet/phones did not automatically refresh when the match controller setup the next match.

That is

  - score auto
  - submit auto
  - score teleop
  - submit teleop
  - review scores
  - submit scores

At this point the page redirects to a waiting for next match page.  Sometimes it wouldn't refresh to the score auto page and the match would start anyway.

This is problematic if there isn't sufficient communication between the scorekeepers and the person running the match control page.

**Comment by adwiii** [comment]
This was done intentionally - the page is not meant to refresh once the score have been submitted. The Score Tracker is supposed to manually reload the page shortly before the match begins.

The problem here is if you have a multi-field event and a different set of Score Trackers for each field, then you need to be absolutely sure that while Field 2 is running, the Score Trackers from Field 1 are not entering scores. The idea of the Score Tracker having to manually reload the page is to have an active confirmation from them that "Yes, I do mean to score this match."

In theory we could make it so that there is a different score tracker page for Field 1 and Field 2 similar to how there are different pages for the Field Timers; however, this would also add another level of complication of the score trackers needing to make sure they are on the correct page throughout the day. For example, if they were to change fields for whatever reason, they would have to remember to change pages.

**Comment by ftctechnh** [comment]
How about the idea of placing a button on the screen to allow them to refresh?  This would still be a manual process, but it might be easier from a user perspective.

When we tested this with some of the staff, one person (who is an iOS user) didn't know how to refresh the page via the Chrome Browser.

**Comment by cmacfarl** [comment]
I see your perspective here.   In order to make the training easier for the score trackers how about redirecting to a page that says, "Do you want to score Qualification Match 26: A,B vs C,D?" with a big YES button below it?

That page would automatically refresh as the matches progress.  So if I was only scoring odd matches, I wouldn't do anything and when match 27 arrived it would ask if I wanted to score that match.

In my testing, in the chaos of a workshop with 20 kids, the score keepers just didn't know when to do what.  We'd want to avoid this during a major competition.
