### ISSUE TITLE
Confusion between auto/teleop live-scoring pages.

### ISSUE THREAD

**Issue by cmacfarl** [adwiii/nc-ftc-inspection-spark#6]
While running some practice matches last weekend I noticed my scorekeepers, more than once, scored teleop glyphs on the autonomous score screen.

Is there a way to ensure that the live-scoring phones move to teleop before the teleop period starts?

I realize that the 5 second auto-start makes this somewhat problematic, forcing the score keepers to be on their game and fast with the scoring.  But it's very, very easy to score the wrong phase of the game.

Alternatively, just perhaps making it abundantly clear to the score keeper which phase they are scoring.  The little bar at the top perhaps isn't sufficient to capture attention.

**Comment by adwiii** [comment]
We cannot make it so that it moves automatically from auto to teleop because information such as parking, jewels, and keys cannot be entered once you have transitioned phases and it is important to make sure this is recorded accurately at the time.

We can attempt to add more indicators to the screen, including making the page flash at you if you are still in auto when teleop has begun, etc. However, these will take some time to implement. In the mean time, there are other indicators on the page, such as the key being bolded in the cryptobox and the lack of row indicators that should also serve as a reminder to the score tracker that they are not in teleop.

Hopefully when we finish the Score Tracker Manual and Score Trackers become more familiar with the software this will become less of an issue.

**Comment by ftctechnh** [comment]
One suggestion that some of the staff that tried the software suggested was to perhaps have different background colors or something stark/noticeable so that the operator will know they are in Auto or TeleOp mode.  Currently, there is only a colored (red or blue) rectangle with the words "Autonomous" or "TeleOp" to distinguish the modes (aside from the differences in the score tracking layout).

**Comment by cmacfarl** [comment]
> and it is important to make sure this is recorded accurately at the time.

I fully agree.  And absent a completely automated scoring system, my biggest concern is that scores will get missed because a score tracker is behind and the 5 second automated, forced, countdown isn't enough time to accurately score autonomous.

Hence my, "alternatively" suggestion which is similar to @ftctechnh.   I like the flashing very much.  Danger Will Robinson, make sure you know what you are doing...
